### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by ShayanMahnam** [ShayanMahnam/team-amazon-clone#29]
We need Authentication for the Sign-in page, When everything else finished.

### Hint and Suggestion 
Have a meeting together, one person creates an account in Firebase and install dependencies:

`npm install firebase`
`npm install firebase-login`
`npm install firebase-tools`

A person who is **driver** should do this and try to install them one by one.

**Comment by VitalinaKuzmenko** [comment]
We’re going to have a meeting on Wednesday at 20:30 together and to do and to finish authentication part.
